apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: taxi
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ0cmlhbHljeHhrZS5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiYTI5MGFUcEJaRzFwYmtBeE1qTT0iCgkJfQoJ
type: kubernetes.io/dockerconfigjson